### ISSUE TITLE
Unable to access data

### ISSUE THREAD

**Issue by vsomnath** [nanand2/protein_seq_des#2]
Hi Namrata, 

First of all, great work and really nice codebase!

I was trying to access the data using GCP (have an account linked with a payment mode), but get the issue (as attached below):
![image](https://user-images.githubusercontent.com/32259379/175884952-85811fdc-2222-48fd-9515-e170b782809b.png)

Would you happen to know a fix for this, or if some permissions need to be changed to make the data visible to everyone?

Thanks and regards,
Vignesh

**Comment by nanand2** [comment]
Hi Vignesh, since I’m no longer in my lab I don’t have control over the lab
GCP. Try emailing ***@***.*** Hopefully they’ve not deleted it…

No need to CC me on those communications

**Comment by gelnesr** [comment]
Hi @vsomnath, 

There has been a lot of shifting happening, sorry for not seeing this concern! We have provided the txt files that were used for training in the lab's repository ([protein_seq_des](https://github.com/ProteinDesignLab/protein_seq_des)). I have opened an issue and will message again when we have updated the repo with an alternative storage system that we actually have control of without a payment mode.

**Comment by vsomnath** [comment]
Perfect, thank you!

**Comment by gelnesr** [comment]
@vsomnath  - Update, data is now available [here](https://drive.google.com/drive/u/0/folders/1MD-tu32SoYtZGag04HwntuxcuOnYPDXs).

**Comment by vsomnath** [comment]
Thank you and sorry for the long delay in responding! Closing this accordingly.
